# MLR (Multiple Linear Regression)

In [32]:
import numpy as np
import pandas as pd


In [33]:
dataframe = pd.read_csv("50_Startups.csv")
dataframe.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

First cleaning the dummy variables:

You should eliminate one dummy variable

In [35]:
# noDummies = pd.get_dummies(dataframe['State'], drop_first=True)
X = dataframe.iloc[:, :-1].values
y = dataframe.iloc[:, -1].values
# CODE TODO

In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder



In [37]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [43]:
from sklearn.model_selection import train_test_split 
# creating train and test sets 
X_train, X_test, y_train, y_test = train_test_split( 
    X, y, test_size=0.2, random_state=101) 

In [44]:
from sklearn.linear_model import LinearRegression 

In [45]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [47]:
# Predicting
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis= 1))

[[ 86894.76  89949.14]
 [153481.03 132602.65]
 [119836.84 111313.02]
 [ 98459.9   97427.84]
 [118555.74 110352.25]
 [189726.   191792.06]
 [114295.31 105733.54]
 [ 61551.3   49490.75]
 [ 70236.86  71498.49]
 [ 47600.77  42559.73]]


### ESTO DE ABAJO ES LO MIO, NO LE HAGAN CASO XD

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
state = LabelEncoder()

In [7]:
numeric_dataframe = dataframe.copy()

In [8]:
numeric_dataframe['State'] = state.fit_transform(dataframe['State'])
numeric_dataframe.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

## MLR

In [15]:
X = numeric_dataframe.iloc[:, :-1].values
y = numeric_dataframe.iloc[:, -1].values


array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [16]:
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [17]:

# creating train and test sets 
X_train, X_test, y_train, y_test = train_test_split( 
    X, y, test_size=0.3, random_state=101) 

In [18]:
# creating a regression model 
model = LinearRegression() 

In [19]:

# fitting the model 
model.fit(X_train,y_train)

LinearRegression()

In [20]:

# making predictions 
predictions = model.predict(X_test) 

In [21]:

# model evaluation 
print( 
  'mean_squared_error : ', mean_squared_error(y_test, predictions)) 
print( 
  'mean_absolute_error : ', mean_absolute_error(y_test, predictions)) 

mean_squared_error :  75220988.7584793
mean_absolute_error :  6801.968394379832
