# Introduction to numpy


In [2]:
import numpy


---

### Data Types and Attributes


In [3]:
# Numpy array
array = numpy.array([1,2,3])
array

array([1, 2, 3])

In [4]:
type(array
)

numpy.ndarray

In [5]:
a2 = numpy.array([[1,2.0, 3.3],
                [3,4,6.5]])

In [6]:
a3 = numpy.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1 = array


In [9]:
array[1]

2

In [10]:
array[1] = 0


In [11]:
a1[1]

0

In [12]:
# You see it works the same as python in arrays :v


In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(3, 2, 3)

In [16]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [17]:
a1.dtype

dtype('int32')

In [18]:
a1.size

3

In [19]:
a2.size, a3.size

(6, 18)

In [20]:
# Size is total elements in the arrays
#No matter what type arrays is an ndarray, an universe datatype

In [21]:
# Create a data frame from a Numpy array
import pandas

KeyboardInterrupt: 

In [ ]:
# Only 2-d or 1-d input
data = pandas.DataFrame(a2)

In [ ]:
data

---

### Creating arrays

In [ ]:
sample_array = numpy.array([1,2,3])

In [ ]:
sample_array

In [22]:
sample_array.dtype

NameError: name 'sample_array' is not defined

In [23]:
# Shift + tab gives you documentation of a functions inside brackets

In [24]:
ones = numpy.ones((3,4))

In [25]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [28]:
zeros = numpy.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
range_arr = numpy.arange(0,10,2)

In [30]:
range_arr


array([0, 2, 4, 6, 8])

In [31]:
rndom = numpy.random.randint(0,10, size = (3,5))
rndom

array([[0, 1, 2, 1, 4],
       [6, 5, 4, 5, 4],
       [4, 0, 7, 3, 1]])

In [32]:
rndom.shape

(3, 5)

In [33]:
rndom.size

15

In [34]:
numpy.random.random((5,3
                ))

array([[0.72717308, 0.4775399 , 0.21214366],
       [0.50527421, 0.72850567, 0.08962585],
       [0.54454353, 0.22178272, 0.29523841],
       [0.55728394, 0.55278024, 0.93981381],
       [0.87239922, 0.2563241 , 0.84326307]])

In [35]:
rndom2 = numpy.random.random((5,3
                ))

In [36]:
rndom2.size


15

In [37]:
rndom = numpy.random.rand(5,3)

In [38]:
rndom

array([[0.05539878, 0.14642297, 0.47154678],
       [0.38627359, 0.2420423 , 0.39946208],
       [0.87990783, 0.68838234, 0.30712907],
       [0.42503931, 0.4774313 , 0.31728369],
       [0.36367638, 0.35550279, 0.45001273]])

In [39]:
# numpy.random.seed()
numpy.random.seed(0)
rndom4 = numpy.random.randint(10, size = (5,3))

In [40]:
rndom4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [41]:
# random seed for having the same randoms that are the same
# numpy.random.seed(0) # or whatever nmumber
# same randoms every time

# 3. Viewing arrays and matrices

---

In [42]:
numpy.unique([1,1,1,1,1,12,23,23])

array([ 1, 12, 23])

In [43]:
a2

array([[1. , 2. , 3.3],
       [3. , 4. , 6.5]])

In [44]:
a2[0]

array([1. , 2. , 3.3])

In [45]:
a1


array([1, 0, 3])

In [46]:
a1[0]

1

In [47]:
a3.shape

(3, 2, 3)

In [48]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [49]:
a3[0][0][0]

1

In [50]:
a3[0,0,0]

1

In [51]:
#differents types of indexing

In [52]:
a3[:3 ,:1, :2]

array([[[ 1,  2]],

       [[ 7,  8]],

       [[13, 14]]])

In [53]:
a4 = numpy.random.randint(10, size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [55]:
a4[1, 0, 0]

array([4, 6, 4, 4, 3])

In [56]:
a4[:,:,:,:1]

array([[[[6],
         [5],
         [3],
         [2]],

        [[3],
         [9],
         [3],
         [0]],

        [[8],
         [8],
         [9],
         [0]]],


       [[[4],
         [4],
         [7],
         [5]],

        [[0],
         [0],
         [5],
         [2]],

        [[2],
         [9],
         [2],
         [0]]]])

## 4.- Manipulating and comparing arrays

---

In [57]:
a1

array([1, 0, 3])

In [58]:
ones = numpy.ones(3)     
ones


array([1., 1., 1.])

In [59]:
a1 + ones

array([2., 1., 4.])

In [60]:
a1 - ones

array([ 0., -1.,  2.])

In [61]:
a1 * a2

array([[ 1. ,  0. ,  9.9],
       [ 3. ,  0. , 19.5]])

In [62]:
a2, a1

(array([[1. , 2. , 3.3],
        [3. , 4. , 6.5]]),
 array([1, 0, 3]))

In [63]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [64]:
a3 * a2

array([[[  1. ,   4. ,   9.9],
        [ 12. ,  20. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 30. ,  44. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 48. ,  68. , 117. ]]])

In [65]:
a3, a2

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 array([[1. , 2. , 3.3],
        [3. , 4. , 6.5]]))

In [66]:
a2 // ones

array([[1., 2., 3.],
       [3., 4., 6.]])

In [67]:
a3 / a2

array([[[ 1.        ,  1.        ,  0.90909091],
        [ 1.33333333,  1.25      ,  0.92307692]],

       [[ 7.        ,  4.        ,  2.72727273],
        [ 3.33333333,  2.75      ,  1.84615385]],

       [[13.        ,  7.        ,  4.54545455],
        [ 5.33333333,  4.25      ,  2.76923077]]])

In [68]:
a2 ** a3


array([[[1.00000000e+00, 4.00000000e+00, 3.59370000e+01],
        [8.10000000e+01, 1.02400000e+03, 7.54188906e+04]],

       [[1.00000000e+00, 2.56000000e+02, 4.64114844e+04],
        [5.90490000e+04, 4.19430400e+06, 5.68800906e+09]],

       [[1.00000000e+00, 1.63840000e+04, 5.99389455e+07],
        [4.30467210e+07, 1.71798692e+10, 4.28983333e+14]]])

In [69]:
a3 ** a2

array([[[1.00000000e+00, 4.00000000e+00, 3.75405076e+01],
        [6.40000000e+01, 6.25000000e+02, 1.14283393e+05]],

       [[7.00000000e+00, 6.40000000e+01, 1.40928971e+03],
        [1.00000000e+03, 1.46410000e+04, 1.03437520e+07]],

       [[1.30000000e+01, 1.96000000e+02, 7.60503391e+03],
        [4.09600000e+03, 8.35210000e+04, 1.44301645e+08]]])

In [70]:
a2 // a3

array([[[1., 1., 1.],
        [0., 0., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [71]:
a2 / a3

array([[[1.        , 1.        , 1.1       ],
        [0.75      , 0.8       , 1.08333333]],

       [[0.14285714, 0.25      , 0.36666667],
        [0.3       , 0.36363636, 0.54166667]],

       [[0.07692308, 0.14285714, 0.22      ],
        [0.1875    , 0.23529412, 0.36111111]]])

In [72]:
a1, a2

(array([1, 0, 3]),
 array([[1. , 2. , 3.3],
        [3. , 4. , 6.5]]))

In [75]:
numpy.add(a1, a2)

array([[2. , 2. , 6.3],
       [4. , 4. , 9.5]])

In [77]:
numpy.mod(a1, a2)

array([[0., 0., 3.],
       [1., 0., 3.]])