# Introduction to numpy


In [1]:
import numpy


---

### Data Types and Attributes


In [2]:
# Numpy array
array = numpy.array([1,2,3])
array

array([1, 2, 3])

In [3]:
type(array
)

numpy.ndarray

In [18]:
a2 = numpy.array([[1,2.0, 3.3],
                [3,4,6.5]])

In [8]:
a3 = numpy.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1 = array


In [12]:
array[1]

2

In [13]:
array[1] = 0


In [14]:
a1[1]

0

In [15]:
# You see it works the same as python in arrays :v


In [16]:
a1.shape

(3,)

In [19]:
a2.shape

(2, 3)

In [20]:
a3.shape

(3, 2, 3)

In [21]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
a1.dtype

dtype('int32')

In [23]:
a1.size

3

In [24]:
a2.size, a3.size

(6, 18)

In [25]:
# Size is total elements in the arrays
#No matter what type arrays is an ndarray, an universe datatype

In [26]:
# Create a data frame from a Numpy array
import pandas

In [33]:
# Only 2-d or 1-d input
data = pandas.DataFrame(a2)

In [34]:
data

0    1    2
0  1.0  2.0  3.3
1  3.0  4.0  6.5

---

### Creating arrays

In [35]:
sample_array = numpy.array([1,2,3])

In [36]:
sample_array

array([1, 2, 3])

In [37]:
sample_array.dtype

dtype('int32')

In [38]:
# Shift + tab gives you documentation of a functions

In [40]:
ones = numpy.ones((3,4))

In [41]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
ones.dtype

dtype('float64')